kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alfresco-volume-claim
  namespace: aps
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi