ingress:
  hostName: "52.170.160.221"
  protocol: http

license:
  secretName: licenseaps

adminApp:
  environment:
    ACTIVITI_ADMIN_REST_APP_HOST: '{{ .Values.ingress.protocol }}://{{ .Values.ingress.hostName }}'
  image:
    repository: quay.io/alfresco/alfresco-process-services-admin
  ingress:
    hostName: '{{ .Values.ingress.hostName }}'

alfresco-process-services:
  alfresco-infrastructure:
    enabled: false

processEngine:
  image:
    repository: quay.io/alfresco/alfresco-process-services
    tag: 1.10.0
  ingress:
    hostName: '{{ .Values.ingress.hostName }}'

processWorkspace:
  image:
    repository: quay.io/alfresco/alfresco-process-workspace-app
    tag: 1.3.4
  ingress:
    hostName: '{{ .Values.ingress.hostName }}'
