controller:
  name: controller
  image:
    repository: quay-io.artifact.swissre.com/kubernetes-ingress-controller/nginx-ingress-controller

defaultBackend:
  image:
    repository: k8s-gcr-io.artifact.swissre.com/defaultbackend-amd64
